### ISSUE TITLE
mypy preflight check failed

### ISSUE THREAD

**Issue by Johannes-Kutsch** [Johannes-Kutsch/pycastle#495]
## Root cause

The mypy errors are a known broken state introduced by commit 11d8cff (fix #490: rebirth GithubService as urllib HTTP transport). That commit replaced the subprocess-based `GithubService` with a new urllib-based transport but, per its coordination note, intentionally left the typed method surface (`get_open_issues`, `get_issue_title`, `close_issue`, `close_completed_parent_issues`, `has_open_issues_with_label`) and the removed `GithubNotFoundError` exception out of the new class. It also changed the constructor signature to require a positional `token` argument.

The remaining call sites (`src/pycastle/orchestrator.py`, `src/pycastle/iteration/preflight.py`, `src/pycastle/iteration/merge.py`, `tests/test_orchestrator.py`) and `labels.py` were intentionally not updated, so they no longer type-check against the new `GithubService`.

The 10 errors split into:

- `src/pycastle/iteration/preflight.py:121,144` — `get_open_issues`, `get_issue_title` not on new transport.
- `src/pycastle/iteration/merge.py:80,87,139,140` — `close_issue`, `close_completed_parent_issues` not on new transport.
- `src/pycastle/orchestrator.py:14` — `GithubNotFoundError` no longer exported from `pycastle.services` (replaced by `GithubAuthError` / `GithubAPIError` / `GithubNetworkError`).
- `src/pycastle/orchestrator.py:155` — instantiates `GithubService(...)` without the now-required `token` arg.
- `src/pycastle/orchestrator.py:167` — `has_open_issues_with_label` not on new transport.
- `tests/test_orchestrator.py:21` — imports the removed `GithubNotFoundError`.

This is a coordination gap, not an unrelated regression.

## Intended behavior

`mypy .` passes with zero errors. The HTTP-based `GithubService` exposes the full method surface that `orchestrator.py`, `labels.py`, `iteration/preflight.py`, and `iteration/merge.py` rely on, and those call sites are migrated to the new constructor signature and the new typed exceptions.

## Fix prescription

Land the already-filed follow-ups in order:

1. **#491** (Migrate GithubService method surface + add label methods on new transport) — reintroduces `get_open_issues`, `get_issue_title`, `close_issue`, `close_completed_parent_issues`, `has_open_issues_with_label`, `get_open_sub_issues`, `get_parent`, `get_open_issue_numbers`, `get_labels`, plus the new label methods, all on `_request` / `_paginate`. Resolves the four `preflight.py` and `merge.py` errors plus the `has_open_issues_with_label` error in `orchestrator.py`.
2. **#492** (Orchestrator: eager GithubService + check_auth preflight, remove gh machinery) — rewrites `orchestrator.py` to instantiate `GithubService(repo, token, cfg)` with the resolved token, drops `gh auth status` / `_get_repo`, and replaces the `GithubNotFoundError` import with the new typed exceptions. Updates `tests/test_orchestrator.py` accordingly. Resolves the remaining three `orchestrator.py` errors and the test import.
3. **#493** (labels.py rewrite) — separately covered, not strictly needed to fix mypy today since `labels.py` did not appear in this run, but should land in the same coordinated wave to keep the call-site migration consistent.

No band-aid (no shims, no `# type: ignore`, no resurrection of `GithubNotFoundError`) — the fix is purely to complete the in-flight migration. Once #491 and #492 merge, `mypy .` will return to green.

## Reproduction

**Command:** ` mypy .`

**Output:**
\`\`\`
Command failed (exit 1):
src/pycastle/iteration/preflight.py:121: error: \"GithubService\" has no attribute \"get_open_issues\"  [attr-defined]
src/pycastle/iteration/preflight.py:144: error: \"GithubService\" has no attribute \"get_issue_title\"  [attr-defined]
src/pycastle/iteration/merge.py:80: error: \"GithubService\" has no attribute \"close_issue\"  [attr-defined]
src/pycastle/iteration/merge.py:87: error: \"GithubService\" has no attribute \"close_completed_parent_issues\"  [attr-defined]
src/pycastle/iteration/merge.py:139: error: \"GithubService\" has no attribute \"close_issue\"  [attr-defined]
src/pycastle/iteration/merge.py:140: error: \"GithubService\" has no attribute \"close_completed_parent_issues\"  [attr-defined]
src/pycastle/orchestrator.py:14: error: Module \"pycastle.services\" has no attribute \"GithubNotFoundError\"; maybe \"GitNotFoundError\"?  [attr-defined]
src/pycastle/orchestrator.py:155: error: Missing positional argument \"token\" in call to \"GithubService\"  [call-arg]
src/pycastle/orchestrator.py:167: error: \"GithubService\" has no attribute \"has_open_issues_with_label\"  [attr-defined]
tests/test_orchestrator.py:21: error: Module \"pycastle.services\" has no attribute \"GithubNotFoundError\"; maybe \"GitNotFoundError\"?  [attr-defined]
Found 10 errors in 4 files (checked 73 source files)
\`\`\`

(The full mypy output also contains many `[annotation-unchecked]` notes about untyped test bodies — those are notes, not errors, and unrelated to this failure.)

Note: this is the same broken state explicitly called out in commit 11d8cff. Existing tracking issues #491 and #492 already specify the fix in detail.
